services:
    fpm:
        build: .
        volumes:
          - '.env:/app/.env'
        networks:
            - lincoln
        environment:
            - APP_ENV=production
            - DB_CONNECTION=mysql
            - DB_HOST=database
            - DB_PORT=3306
            - DB_DATABASE=lincoln
            - DB_USERNAME=lincoln
            - DB_PASSWORD=lincoln
    web:
        image: caddy:latest
        volumes:
            - ".:/app"
            - "./deploy/Caddyfile:/etc/caddy/Caddyfile"
        ports:
            - "80:80"
            - "443:443"
        networks:
            - lincoln
    database:
        image: mysql:8
        environment:
            - MYSQL_USER=lincoln
            - MYSQL_PASSWORD=lincoln
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=lincoln
networks:
    lincoln:
